# Generated by Django 5.1 on 2024-09-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainChess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='players',
            name='profile_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='rating',
            field=models.IntegerField(default=400),
        ),
    ]
