# Generated by Django 5.1 on 2024-09-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainChess', '0002_players_avatar_players_profile_link_players_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
