# Generated by Django 5.1 on 2024-09-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainChess', '0003_players_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('max_participants', models.IntegerField()),
                ('current_participants', models.IntegerField(default=0)),
            ],
        ),
    ]
