# Generated by Django 5.1 on 2024-09-25 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainChess', '0007_tournamentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='additional_info',
            field=models.TextField(default='Турнир проводится в Лондонском шахматном клубе.'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='contact_email',
            field=models.EmailField(default='info@chesslondon2024.com', max_length=254),
        ),
        migrations.AddField(
            model_name='tournament',
            name='contact_phone',
            field=models.CharField(default='+44 123 456 789', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_description',
            field=models.TextField(default='Призовой фонд будет распределён среди победителей турнира.'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_fund',
            field=models.CharField(default='50,000 фунтов', max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_info',
            field=models.TextField(default='Регистрация доступна до 1 октября 2024 года.'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rules_description',
            field=models.TextField(default='Контроль времени на каждую партию: 90 минут.'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rules_title',
            field=models.CharField(default='Швейцарская система в 7 туров', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(default='2024-10-10'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='location',
            field=models.CharField(default='Лондон, Великобритания', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_participants',
            field=models.IntegerField(default=32),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='Шахматный Турнир', max_length=255),
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=255)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='MainChess.tournament')),
            ],
        ),
    ]
