# Generated by Django 5.1 on 2024-09-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainChess', '0008_tournament_additional_info_tournament_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='schedulee',
            field=models.TextField(default='0'),
        ),
    ]
