# Generated by Django 5.1 on 2024-09-25 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainChess', '0009_tournament_schedulee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='schedulee',
            new_name='schedule',
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to='MainChess.tournament'),
        ),
    ]
